# Generated by Django 4.2 on 2023-04-24 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChartPNG",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(verbose_name=django.utils.timezone.now),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("path", models.CharField(max_length=1024)),
                ("params", models.JSONField()),
            ],
            options={
                "verbose_name_plural": "Chart PNGs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Email",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(verbose_name=django.utils.timezone.now),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("to", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=255)),
                ("html_message", models.TextField()),
                ("sender", models.EmailField(max_length=254)),
                ("reply_to", models.EmailField(max_length=254)),
                ("message_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("q", "Queued"),
                            ("s", "Sent"),
                            ("d", "Delivered"),
                            ("dd", "Delivery Delayed"),
                            ("c", "Complained"),
                            ("b", "Bounced"),
                            ("o", "Opened"),
                            ("cl", "Clicked"),
                        ],
                        default="q",
                        max_length=2,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("t", "Test"), ("l", "Live")],
                        default="l",
                        max_length=1,
                    ),
                ),
                (
                    "client",
                    models.CharField(
                        choices=[("r", "Resend"), ("s", "SES")],
                        default="r",
                        max_length=1,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emails",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Emails",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmailChartPNG",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(verbose_name=django.utils.timezone.now),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "chart_png",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="c_email_chart_pngs",
                        to="emails.chartpng",
                    ),
                ),
                (
                    "email",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="e_email_chart_pngs",
                        to="emails.email",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Email Chart PNGs",
                "unique_together": {("email", "chart_png")},
            },
        ),
        migrations.AddField(
            model_name="chartpng",
            name="emails",
            field=models.ManyToManyField(
                related_name="chart_pngs",
                through="emails.EmailChartPNG",
                to="emails.email",
            ),
        ),
        migrations.AddField(
            model_name="chartpng",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chart_pngs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
