# Generated by Django 4.2 on 2023-04-27 06:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emails", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="email",
            name="client",
            field=models.CharField(
                choices=[("r", "Resend")], default="r", max_length=1
            ),
        ),
    ]
