# Generated by Django 4.2 on 2023-04-18 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("emails", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailchartpng",
            name="email",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="emails.email",
            ),
        ),
    ]
