# Generated by Django 4.2 on 2023-04-18 11:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emails", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chartpng",
            name="email",
        ),
        migrations.AddField(
            model_name="chartpng",
            name="email",
            field=models.ManyToManyField(related_name="chart_pngs", to="emails.email"),
        ),
    ]
