# Generated by Django 4.2 on 2023-04-25 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emails", "0002_alter_chartpng_created_at_alter_email_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="email",
            name="plain_message",
            field=models.TextField(default="hello"),
            preserve_default=False,
        ),
    ]
