# Generated by Django 4.2 on 2023-04-18 11:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("emails", "0002_remove_chartpng_email_chartpng_email"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chartpng",
            old_name="email",
            new_name="emails",
        ),
    ]
