# Generated by Django 4.2 on 2023-04-20 05:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emails", "0002_alter_emailchartpng_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="email",
            name="status",
            field=models.CharField(
                choices=[
                    ("q", "Queued"),
                    ("s", "Sent"),
                    ("d", "Delivered"),
                    ("dd", "Delivery Delayed"),
                    ("c", "Complained"),
                    ("b", "Bounced"),
                    ("o", "Opened"),
                    ("cl", "Clicked"),
                ],
                default="q",
                max_length=2,
            ),
        ),
    ]
