# Generated by Django 4.2 on 2023-04-18 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Channel",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    models.CharField(max_length=24, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=255)),
                ("thumbnail", models.URLField()),
                ("subscriber_count", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="channels",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    models.CharField(
                        editable=False, max_length=11, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=100, null=True)),
                ("thumbnail", models.URLField(blank=True, null=True)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="yt.channel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DailyViews",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("country_code", models.CharField(max_length=2)),
                ("views", models.PositiveBigIntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_views",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_views",
                        to="yt.video",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Daily Views",
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="AccessKeys",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("access_token", models.CharField(max_length=2048)),
                ("valid_till", models.PositiveIntegerField()),
                ("refresh_token", models.CharField(max_length=512)),
                ("is_refresh_valid", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_keys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Access Keys",
                "ordering": ["-created_at"],
            },
        ),
    ]
