# Generated by Django 4.2 on 2023-05-02 16:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("yt", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DemographicsViews",
            new_name="Demographics",
        ),
        migrations.AlterModelOptions(
            name="dailyviews",
            options={
                "ordering": ["date", "video__published_at"],
                "verbose_name_plural": "Daily Views",
            },
        ),
    ]
