# Generated by Django 4.2 on 2023-04-21 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("yt", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="description",
            field=models.TextField(default="hello"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="video",
            name="thumbnail",
            field=models.URLField(default="https://google.com"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="video",
            name="title",
            field=models.CharField(default="hello, 123", max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="DemographicsViews",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("country_code", models.CharField(max_length=2)),
                ("age_group", models.CharField(max_length=20)),
                ("views", models.PositiveBigIntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demographics_views",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demographics_views",
                        to="yt.video",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Demographics Views",
                "ordering": ["age_group"],
            },
        ),
    ]
