# Generated by Django 4.2 on 2023-04-24 08:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("yt", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="accesskeys",
            old_name="valid_till",
            new_name="expires_at",
        ),
    ]
