# Generated by Django 4.2 on 2023-04-22 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("yt", "0002_video_description_alter_video_thumbnail_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="demographicsviews",
            name="views",
        ),
        migrations.AddField(
            model_name="demographicsviews",
            name="gender",
            field=models.CharField(
                choices=[("m", "Male"), ("f", "Female"), ("u", "User Unspecified")],
                default="f",
                max_length=1,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="demographicsviews",
            name="viewer_percentage",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="demographicsviews",
            name="age_group",
            field=models.CharField(
                choices=[
                    ("age13-17", "13-17"),
                    ("age18-24", "18-24"),
                    ("age25-34", "25-34"),
                    ("age35-44", "35-44"),
                    ("age45-54", "45-54"),
                    ("age55-64", "55-64"),
                    ("age65-", "65-"),
                ],
                max_length=10,
            ),
        ),
    ]
