# Generated by Django 4.2 on 2023-05-02 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("yt", "0002_rename_demographicsviews_demographics_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="demographics",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="u_demographics",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="demographics",
            name="video",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="v_demographics",
                to="yt.video",
            ),
        ),
    ]
