# Generated by Django 4.2 on 2023-05-03 05:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("yt", "0003_alter_demographics_user_alter_demographics_video"),
    ]

    operations = [
        migrations.CreateModel(
            name="FetchStatus",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_fetching_at", models.DateTimeField(blank=True, null=True)),
                ("fetched_at", models.DateTimeField(blank=True, null=True)),
                ("is_daily_views_fetching", models.BooleanField(default=False)),
                ("is_demographics_fetching", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fetch_status",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Fetch Statuses",
                "ordering": ["-fetched_at"],
            },
        ),
    ]
